// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvqTRQ6ZbISApSi12rp-rB_F9xfa7Qykw',
    appId: '1:641684678451:web:a824efe1911b1c64fec046',
    messagingSenderId: '641684678451',
    projectId: 'birdfeeder-b6224',
    authDomain: 'birdfeeder-b6224.firebaseapp.com',
    storageBucket: 'birdfeeder-b6224.firebasestorage.app',
    measurementId: 'G-BYDPQXEVNY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArCZAb4X2RjjHNX2vQ47n-IMYtS8DRlFY',
    appId: '1:641684678451:ios:6e100300a5446ce4fec046',
    messagingSenderId: '641684678451',
    projectId: 'birdfeeder-b6224',
    storageBucket: 'birdfeeder-b6224.firebasestorage.app',
    iosBundleId: 'com.example.birdFeederApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArCZAb4X2RjjHNX2vQ47n-IMYtS8DRlFY',
    appId: '1:641684678451:ios:6e100300a5446ce4fec046',
    messagingSenderId: '641684678451',
    projectId: 'birdfeeder-b6224',
    storageBucket: 'birdfeeder-b6224.firebasestorage.app',
    iosBundleId: 'com.example.birdFeederApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvqTRQ6ZbISApSi12rp-rB_F9xfa7Qykw',
    appId: '1:641684678451:web:8e7afd326c3db750fec046',
    messagingSenderId: '641684678451',
    projectId: 'birdfeeder-b6224',
    authDomain: 'birdfeeder-b6224.firebaseapp.com',
    storageBucket: 'birdfeeder-b6224.firebasestorage.app',
    measurementId: 'G-8VD6CSCF1X',
  );

}